// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    [Table("AR_LiveSession")]
    [Index(nameof(ObjectId), Name = "IX_AR_LiveSession")]
    [Index(nameof(MachineName), Name = "IX_AR_LiveSession1")]
    [Index(nameof(ApplicationName), Name = "IX_AR_LiveSession2")]
    [Index(nameof(SessionId), Name = "IX_AR_LiveSession3")]
    public partial class ArLiveSession
    {
        [Column("ID")]
        public int Id { get; set; }
        [Column("ObjectID")]
        public int? ObjectId { get; set; }
        [StringLength(100)]
        public string HostName { get; set; }
        [StringLength(50)]
        public string MachineName { get; set; }
        [StringLength(100)]
        public string ApplicationName { get; set; }
        [Column("SessionID")]
        [StringLength(50)]
        public string SessionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ValidTo { get; set; }
    }
}