// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Table("AR_Object")]
    [Index(nameof(ObjectAlias), Name = "IX_AR_Object")]
    [Index(nameof(ObjectTypeId), Name = "IX_AR_Object_1")]
    [Index(nameof(ObjectName), Name = "IX_AR_Object_2")]
    [Index(nameof(ObjectDescription), Name = "IX_AR_Object_3")]
    [Index(nameof(ObjectCustomField2), Name = "IX_AR_Object_4")]
    [Index(nameof(ObjectCustomField1), Name = "IX_AR_Object_5")]
    public partial class ArObject
    {
        public ArObject()
        {
            ArLogByObjects = new HashSet<ArLog>();
            ArLogToObjects = new HashSet<ArLog>();
            ArPropertyValueObjects = new HashSet<ArPropertyValue>();
            ArPropertyValueProperties = new HashSet<ArPropertyValue>();
            ArReferences = new HashSet<ArReference>();
            ArRelationshipChildObjects = new HashSet<ArRelationship>();
            ArRelationshipParentObjects = new HashSet<ArRelationship>();
        }

        [Key]
        [Column("ObjectID")]
        public int ObjectId { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectName { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectAlias { get; set; }
        [Column("ObjectTypeID")]
        public int ObjectTypeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ObjectValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ObjectValidTo { get; set; }
        [StringLength(255)]
        public string ObjectDescription { get; set; }
        [StringLength(255)]
        public string ObjectCustomField1 { get; set; }
        public Guid? ObjectCustomField2 { get; set; }
        [Column("OwnerID")]
        public int? OwnerId { get; set; }

        [ForeignKey(nameof(ObjectTypeId))]
        [InverseProperty(nameof(ArObjectType.ArObjects))]
        public virtual ArObjectType ObjectType { get; set; }
        [InverseProperty("Object")]
        public virtual ArUser ArUser { get; set; }
        [InverseProperty(nameof(ArLog.ByObject))]
        public virtual ICollection<ArLog> ArLogByObjects { get; set; }
        [InverseProperty(nameof(ArLog.ToObject))]
        public virtual ICollection<ArLog> ArLogToObjects { get; set; }
        [InverseProperty(nameof(ArPropertyValue.Object))]
        public virtual ICollection<ArPropertyValue> ArPropertyValueObjects { get; set; }
        [InverseProperty(nameof(ArPropertyValue.Property))]
        public virtual ICollection<ArPropertyValue> ArPropertyValueProperties { get; set; }
        [InverseProperty(nameof(ArReference.ReferenceApplication))]
        public virtual ICollection<ArReference> ArReferences { get; set; }
        [InverseProperty(nameof(ArRelationship.ChildObject))]
        public virtual ICollection<ArRelationship> ArRelationshipChildObjects { get; set; }
        [InverseProperty(nameof(ArRelationship.ParentObject))]
        public virtual ICollection<ArRelationship> ArRelationshipParentObjects { get; set; }
    }
}