// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Table("AR_ObjectType")]
    [Index(nameof(ObjectTypeAlias), Name = "IX_AR_ObjectType")]
    [Index(nameof(ObjectTypeNamespace), Name = "IX_AR_ObjectType_1")]
    public partial class ArObjectType
    {
        public ArObjectType()
        {
            ArObjects = new HashSet<ArObject>();
            ArReferences = new HashSet<ArReference>();
        }

        [Key]
        [Column("ObjectTypeID")]
        public int ObjectTypeId { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeName { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeAlias { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeNamespace { get; set; }

        [InverseProperty(nameof(ArObject.ObjectType))]
        public virtual ICollection<ArObject> ArObjects { get; set; }
        [InverseProperty(nameof(ArReference.ReferenceObjectType))]
        public virtual ICollection<ArReference> ArReferences { get; set; }
    }
}