// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Table("AR_PropertyValue")]
    [Index(nameof(PropertyValueLtd), Name = "IX_AR_PropertyValue")]
    [Index(nameof(PropertyId), Name = "IX_AR_PropertyValue_1")]
    public partial class ArPropertyValue
    {
        [Key]
        [Column("ObjectID")]
        public int ObjectId { get; set; }
        [Key]
        [Column("PropertyID")]
        public int PropertyId { get; set; }
        [StringLength(3500)]
        public string PropertyValue { get; set; }
        public string PropertyValueLtd { get; set; }

        [ForeignKey(nameof(ObjectId))]
        [InverseProperty(nameof(ArObject.ArPropertyValueObjects))]
        public virtual ArObject Object { get; set; }
        [ForeignKey(nameof(PropertyId))]
        [InverseProperty(nameof(ArObject.ArPropertyValueProperties))]
        public virtual ArObject Property { get; set; }
    }
}