// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Table("AR_Reference")]
    public partial class ArReference
    {
        [Key]
        [Column("ReferenceID")]
        public int ReferenceId { get; set; }
        [Required]
        [StringLength(255)]
        public string ReferenceAlias { get; set; }
        [Column("ReferenceObjectTypeID")]
        public int ReferenceObjectTypeId { get; set; }
        [Column("ReferenceApplicationID")]
        public int? ReferenceApplicationId { get; set; }
        [StringLength(2000)]
        public string ReferenceNotification { get; set; }
        [Required]
        [StringLength(4000)]
        public string ReferenceTestQuery { get; set; }

        [ForeignKey(nameof(ReferenceApplicationId))]
        [InverseProperty(nameof(ArObject.ArReferences))]
        public virtual ArObject ReferenceApplication { get; set; }
        [ForeignKey(nameof(ReferenceObjectTypeId))]
        [InverseProperty(nameof(ArObjectType.ArReferences))]
        public virtual ArObjectType ReferenceObjectType { get; set; }
    }
}