// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    [Table("AR_RelationshipAll")]
    [Index(nameof(ChildObjectId), Name = "IX_AR_RelationshipAll_1")]
    [Index(nameof(ParentObjectId), nameof(ChildObjectId), Name = "IX_AR_RelationshipAll_2")]
    public partial class ArRelationshipAll
    {
        [Column("ParentObjectID")]
        public int ParentObjectId { get; set; }
        [Column("ChildObjectID")]
        public int ChildObjectId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidTo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RelationshipValidFrom { get; set; }
        [StringLength(3000)]
        public string TransitivePath { get; set; }

        [ForeignKey(nameof(ChildObjectId))]
        public virtual ArObject ChildObject { get; set; }
        [ForeignKey(nameof(ParentObjectId))]
        public virtual ArObject ParentObject { get; set; }
    }
}