// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Table("AR_Relationship")]
    [Index(nameof(RelationshipTypeId), Name = "IX_AR_Relationship")]
    [Index(nameof(ParentObjectId), Name = "IX_AR_Relationship_1")]
    [Index(nameof(ChildObjectId), Name = "IX_AR_Relationship_2")]
    [Index(nameof(ParentObjectId), nameof(ChildObjectId), nameof(RelationshipTypeId), Name = "IX_AR_Relationship_3")]
    public partial class ArRelationship
    {
        [Key]
        [Column("RelationshipID")]
        public int RelationshipId { get; set; }
        [Column("RelationshipTypeID")]
        public int RelationshipTypeId { get; set; }
        [Column("ParentObjectID")]
        public int ParentObjectId { get; set; }
        [Column("ChildObjectID")]
        public int ChildObjectId { get; set; }
        public bool DenyAccess { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime RelationshipValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidTo { get; set; }

        [ForeignKey(nameof(ChildObjectId))]
        [InverseProperty(nameof(ArObject.ArRelationshipChildObjects))]
        public virtual ArObject ChildObject { get; set; }
        [ForeignKey(nameof(ParentObjectId))]
        [InverseProperty(nameof(ArObject.ArRelationshipParentObjects))]
        public virtual ArObject ParentObject { get; set; }
        [ForeignKey(nameof(RelationshipTypeId))]
        [InverseProperty(nameof(ArRelationshipType.ArRelationships))]
        public virtual ArRelationshipType RelationshipType { get; set; }
    }
}