// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_Relationship_SelectResult
    {
        public int RelationshipID { get; set; }
        public int RelationshipTypeID { get; set; }
        public int ParentObjectID { get; set; }
        public int ChildObjectID { get; set; }
        public bool DenyAccess { get; set; }
        public DateTime RelationshipValidFrom { get; set; }
        public DateTime? RelationshipValidTo { get; set; }
    }
}
