// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_ObjectType_SelectResult
    {
        public int ObjectTypeID { get; set; }
        public string ObjectTypeName { get; set; }
        public string ObjectTypeAlias { get; set; }
        public string ObjectTypeNamespace { get; set; }
    }
}
