// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_Relationship_Valid_SelectResult
    {
        public int RelationshipID { get; set; }
        public int RelationshipTypeID { get; set; }
        public int ParentObjectID { get; set; }
        public int ChildObjectID { get; set; }
        public bool DenyAccess { get; set; }
        public DateTime RelationshipValidFrom { get; set; }
        public DateTime? RelationshipValidTo { get; set; }
        public string RelationshipTypeName { get; set; }
        public string RelationshipTypeNamespace { get; set; }
        public string RelationshiptypeAlias { get; set; }
        public string RelationshipTypeDescription { get; set; }
        public bool? Inherit { get; set; }
        public string ChildObjectName { get; set; }
        public string ParentObjectName { get; set; }
        public string ChildObjectAlias { get; set; }
        public string ParentObjectAlias { get; set; }
        public string ChildObjectDescription { get; set; }
        public string ParentObjectDescription { get; set; }
        public string ChildObjectTypeNamespace { get; set; }
        public string ChildObjectTypeAlias { get; set; }
        public string ParentObjectTypeNamespace { get; set; }
        public string ParentObjectTypeAlias { get; set; }
        public string IsChildLocked { get; set; }
        public string IsParentLocked { get; set; }
        public int? OwnerID { get; set; }
    }
}
