// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_PropertyValue_SelectResult
    {
        public int ObjectID { get; set; }
        public int PropertyID { get; set; }
        public string PropertyValue { get; set; }
        public string PropertyValueLtd { get; set; }
        public string ObjectName { get; set; }
        public string ObjectAlias { get; set; }
        public int ObjectTypeID { get; set; }
        public DateTime ObjectValidFrom { get; set; }
        public DateTime? ObjectValidTo { get; set; }
        public string ObjectTypeAlias { get; set; }
        public string ObjectTypeNamespace { get; set; }
        public string ObjectTypeName { get; set; }
        public string ObjectDescription { get; set; }
        public string ObjectCustomField1 { get; set; }
    }
}
