// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_Object_GetPropertiesResult
    {
        public int PropertyID { get; set; }
        public int ObjectID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyAlias { get; set; }
        public string PropertyNamespace { get; set; }
        public string PropertyTypeAlias { get; set; }
        public string ObjectName { get; set; }
        public string ObjectAlias { get; set; }
        public string ObjectTypeAlias { get; set; }
        public string PropertyValue { get; set; }
        public int? OwnerID { get; set; }
    }
}
