// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_Log_SelectResult
    {
        public int LogID { get; set; }
        public DateTime LogTime { get; set; }
        public int ByObjectID { get; set; }
        public int ToObjectID { get; set; }
        public string LogText { get; set; }
        public string EventCode { get; set; }
    }
}
