// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_Object_SelectEffectivePermissionMatrixResult
    {
        public int ID { get; set; }
        public int? ParentObjectID { get; set; }
        public int? ChildObjectID { get; set; }
        public string RelationshipTypeName { get; set; }
        public string RelationshipTypeAlias { get; set; }
        public string Status { get; set; }
        public string ChildObjectName { get; set; }
        public string ChildObjectAlias { get; set; }
        public string ChildObjectTypeName { get; set; }
        public string ParentObjectName { get; set; }
        public string ParentObjectAlias { get; set; }
        public string ParentObjectTypeName { get; set; }
        public string ChildObject { get; set; }
        public string ParentObject { get; set; }
    }
}
