// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_UserGroup_ListResult
    {
        public int ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectDescription { get; set; }
        public string IsLocked { get; set; }
        public int? OwnerID { get; set; }
        public string ObjectAlias { get; set; }
    }
}
