// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_RelationshipAll_Valid_SelectResult
    {
        public int ParentObjectID { get; set; }
        public int ChildObjectID { get; set; }
        public DateTime? RelationshipValidTo { get; set; }
        public DateTime? RelationshipValidFrom { get; set; }
        public string TransitivePath { get; set; }
    }
}
