// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PETAS.Models.Domain.SecureAccess
{
    public partial class Proc_AR_RelationshipType_DeleteResult
    {
    }
}
