// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArLog
    {
        [Column("LogID")]
        public int LogId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LogTime { get; set; }
        [Column("ByObjectID")]
        public int ByObjectId { get; set; }
        [Column("ToObjectID")]
        public int ToObjectId { get; set; }
        [StringLength(3500)]
        public string LogText { get; set; }
        [StringLength(100)]
        public string EventCode { get; set; }
    }
}