// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArRelationshipAllChildValid
    {
        [Column("ObjectID")]
        public int? ObjectId { get; set; }
        [StringLength(255)]
        public string ObjectName { get; set; }
        [StringLength(255)]
        public string ObjectAlias { get; set; }
        [StringLength(255)]
        public string ObjectDescription { get; set; }
        [Column("ObjectTypeID")]
        public int? ObjectTypeId { get; set; }
        [StringLength(255)]
        public string ObjectCustomField1 { get; set; }
        public Guid? ObjectCustomField2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ObjectValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ObjectValidTo { get; set; }
        [StringLength(255)]
        public string ObjectTypeNamespace { get; set; }
        [StringLength(255)]
        public string ObjectTypeAlias { get; set; }
        [Column("parentobjectID")]
        public int ParentobjectId { get; set; }
        [Column("childObjectID")]
        public int ChildObjectId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidTo { get; set; }
        [StringLength(3032)]
        public string TransitivePath { get; set; }
        [Column("OwnerID")]
        public int? OwnerId { get; set; }
    }
}