// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArPropertyValueJoinedMatrix
    {
        [Column("PropertyID")]
        public int PropertyId { get; set; }
        [Column("ObjectID")]
        public int ObjectId { get; set; }
        [Required]
        [StringLength(255)]
        public string PropertyName { get; set; }
        [Required]
        [StringLength(255)]
        public string PropertyAlias { get; set; }
        [Required]
        [StringLength(255)]
        public string PropertyNamespace { get; set; }
        [Required]
        [StringLength(255)]
        public string PropertyTypeAlias { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectName { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectAlias { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeAlias { get; set; }
        [StringLength(3500)]
        public string PropertyValue { get; set; }
        [Column("OwnerID")]
        public int? OwnerId { get; set; }
    }
}