// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArLogJoined
    {
        [Column("LogID")]
        public int LogId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LogTime { get; set; }
        [Column("ByObjectID")]
        public int ByObjectId { get; set; }
        [Column("ToObjectID")]
        public int ToObjectId { get; set; }
        [StringLength(3500)]
        public string LogText { get; set; }
        [StringLength(100)]
        public string EventCode { get; set; }
        [StringLength(255)]
        public string ByObjectName { get; set; }
        [StringLength(255)]
        public string ByObjectAlias { get; set; }
        [StringLength(255)]
        public string ToObjectName { get; set; }
        [StringLength(255)]
        public string ToObjectAlias { get; set; }
        [Column("OwnerID")]
        public int? OwnerId { get; set; }
        [Column("ByOwnerID")]
        public int? ByOwnerId { get; set; }
        [Column("ToOwnerID")]
        public int? ToOwnerId { get; set; }
    }
}