// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArPropertyValueJoined
    {
        [Column("ObjectID")]
        public int? ObjectId { get; set; }
        [Column("PropertyID")]
        public int? PropertyId { get; set; }
        [StringLength(3500)]
        public string PropertyValue { get; set; }
        [StringLength(450)]
        public string PropertyValueLtd { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectName { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectAlias { get; set; }
        [Column("ObjectTypeID")]
        public int ObjectTypeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ObjectValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ObjectValidTo { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeAlias { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeNamespace { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeName { get; set; }
        [StringLength(255)]
        public string ObjectDescription { get; set; }
        [StringLength(255)]
        public string ObjectCustomField1 { get; set; }
        [Column("OwnerID")]
        public int? OwnerId { get; set; }
    }
}