// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArLiveSession
    {
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(100)]
        public string HostName { get; set; }
        [StringLength(50)]
        public string MachineName { get; set; }
        [StringLength(100)]
        public string ApplicationName { get; set; }
        [Column("SessionID")]
        [StringLength(50)]
        public string SessionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ValidTo { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string IsLocked { get; set; }
        [Column("ObjectID")]
        public int? ObjectId { get; set; }
        [StringLength(255)]
        public string ObjectName { get; set; }
        [StringLength(255)]
        public string ObjectAlias { get; set; }
        [StringLength(513)]
        public string UniqueName { get; set; }
    }
}