// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArObjectType
    {
        [Column("ObjectTypeID")]
        public int ObjectTypeId { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeName { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeAlias { get; set; }
        [Required]
        [StringLength(255)]
        public string ObjectTypeNamespace { get; set; }
    }
}