// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArRoleMatrix
    {
        [Column("ParentObjectID")]
        public int ParentObjectId { get; set; }
        [Column("ChildObjectID")]
        public int ChildObjectId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidTo { get; set; }
        [StringLength(255)]
        public string ParentObjectAlias { get; set; }
        [Column("ParentObjectTypeID")]
        public int? ParentObjectTypeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ParentObjectValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ParentObjectValidTo { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string IsLocked { get; set; }
        [StringLength(255)]
        public string ChildObjectAlias { get; set; }
        [Column("ChildObjectTypeID")]
        public int? ChildObjectTypeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChildObjectValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChildObjectValidTo { get; set; }
    }
}