// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArRelationshipAllValid
    {
        [Column("ParentObjectID")]
        public int ParentObjectId { get; set; }
        [Column("ChildObjectID")]
        public int ChildObjectId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidTo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidFrom { get; set; }
        [StringLength(3032)]
        public string TransitivePath { get; set; }
    }
}