// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArRelationshipAll
    {
        [Column("parentobjectid")]
        public int Parentobjectid { get; set; }
        [Column("childobjectid")]
        public int Childobjectid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RelationshipValidTo { get; set; }
    }
}