// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PETAS.Models.Domain.SecureAccess
{
    [Keyless]
    public partial class ViewArPropertyValue
    {
        [Column("ObjectID")]
        public int ObjectId { get; set; }
        [Column("PropertyID")]
        public int PropertyId { get; set; }
        [StringLength(3500)]
        public string PropertyValue { get; set; }
        [StringLength(450)]
        public string PropertyValueLtd { get; set; }
    }
}